const data = {
  cake: [
  {
    name: "​THE SIGNATURE CHOCOLATE CAKE",
    description: "LAYERED BOURBON CHOCOLATE SPONGE. VANILLA BEAN MASCARPONE FILLING. ​SEMI-NAKED WITH VANILLA BEAN BUTTERCREAM. OUR #1 SELLER-- MOST REQUESTED CAKE!"
  },
  {
    name: "CHOCOLATE CHIP",
    description: "LAYERED CHOCOLATE CHIP SPONGE. VANILLA BEAN MASCARPONE FILLING. SEMI-NAKED WITH BROWN BUTTER BUTTERCREAM. DECORATED WITH CRUSHED COOKIES."
  },
  {
    name: "MADAGASCAR VANILLA BEAN",
    description: "LAYERED VANILLA BEAN SPONGE. VANILLA BEAN MASCARPONE FILLING. SEMI-NAKED WITH VANILLA BEAN BUTTERCREAM."
  },
  {
    name: "*LEMON CURD",
    description: "LAYERED LEMON SPONGE. LEMON CURD & MASCARPONE FILLING. SEMI-NAKED WITH LEMON ZEST BUTTERCREAM. TOPPED WITH LEMON CURD."
  }
 ],

 cupcakes: [
   {
     name: "​​BOURBON CHOCOLATE",
     description: "BOURBON CHOCOLATE SPONGE. PIPED WITH VANILLA BEAN MASCARPONE FROSTING.  ​OUR #1 SELLER-- MOST REQUESTED CUPCAKE!​",
   },
   {
    name: "​​CHOCOLATE CHIP",
    description: "CHOCOLATE CHIP SPONGE.  PIPED WITH BROWN BUTTER BUTTERCREAM.  TOPPED WITH CHOCOLATE SHAVINGS.  BROWN SUGAR MASCARPONE ​FROSTING AVAILABLE. ",
  },
  {
    name: "​MADAGASCAR VANILLA BEAN",
    description: "VANILLA BEAN SPONGE.  PIPED WITH VANILLA BEAN MASCARPONE FROSTING.  ​VANILLA BEAN BUTTERCREAM FROSTING AVAILABLE. ",
  },
  {
    name:"*LEMON CURD",
    description:"LEMON ZEST SPONGE.  PIPED WITH LEMON ZEST MASCARPONE FROSTING.  ​TOPPED WITH LEMON CURD.​ "
  }
 ]

} 
 export default data
