const data =  [
  {
    name: "​THE SIGNATURE CHOCOLATE CAKE",
    description: "LAYERED BOURBON CHOCOLATE SPONGE. VANILLA BEAN MASCARPONE FILLING. ​SEMI-NAKED WITH VANILLA BEAN BUTTERCREAM. OUR #1 SELLER-- MOST REQUESTED CAKE!"
  },
  {
    name: "CHOCOLATE CHIP",
    description: "LAYERED CHOCOLATE CHIP SPONGE. VANILLA BEAN MASCARPONE FILLING. SEMI-NAKED WITH BROWN BUTTER BUTTERCREAM. DECORATED WITH CRUSHED COOKIES."
  },
  {
    name: "MADAGASCAR VANILLA BEAN",
    description: "LAYERED VANILLA BEAN SPONGE. VANILLA BEAN MASCARPONE FILLING. SEMI-NAKED WITH VANILLA BEAN BUTTERCREAM."
  },
  {
    name: "*LEMON CURD",
    description: "LAYERED LEMON SPONGE. LEMON CURD & MASCARPONE FILLING. SEMI-NAKED WITH LEMON ZEST BUTTERCREAM. TOPPED WITH LEMON CURD."
  }
 ]

 export default data
 